import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ReduxProvider from '@/_components/ReduxProvider';
import Header from '@/_components/Header';
import StyledComponentsRegistry from '@/_components/Registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: { width: '' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
    <body className={inter.className}>
    <StyledComponentsRegistry>
      <ReduxProvider>
        <Header />
        {children}
      </ReduxProvider>
    </StyledComponentsRegistry>
    </body>
    </html>
  );
}
